# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atucci <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/19 09:05:40 by atucci            #+#    #+#              #
#    Updated: 2023/12/19 09:23:22 by atucci           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = miniHell
FLAG = -Wall -Werror -Wextra

minihell: excevve.c
	gcc $(FLAG) excevve.c -o $(NAME) -lreadline

clean:
	rm miniHell
